export const myProducts = [
  {
    id: 'LxVxPA1LOVM',
    productInfo: {
      name: 'Electric Air – Gray',
      brand: 'Nike',
      category: 'Running',
      price: 90,
      sizes: [
        { mens: 5, available: true },
        { mens: 6, available: true },
        { mens: 7, available: true },
        { mens: 8, available: true },
        { mens: 9, available: false },
        { mens: 10, available: false },
        { mens: 11, available: true },
        { mens: 12, available: false },
        { mens: 13, available: true },
        { mens: 14, available: true },
      ],
      dateListed: 1638028678376,
    },
  },
  {
    id: 'LG88A2XgIXY',
    productInfo: {
      name: 'Lanemaster – Orange',
      brand: 'Nike',
      category: 'Lifestyle',
      price: 75,
      salePrice: 60,
      sizes: [
        { mens: 4, available: true },
        { mens: 5, available: true },
        { mens: 6, available: true },
        { mens: 7, available: false },
        { mens: 8, available: true },
        { mens: 9, available: true },
        { mens: 10, available: true },
        { mens: 11, available: true },
        { mens: 12, available: true },
        { mens: 13, available: true },
      ],
      dateListed: 1638028678375,
    },
  },
  {
    id: 'vraH9m7hfHU',
    productInfo: {
      name: 'Air Quotes',
      brand: 'Nike',
      category: 'Skate',
      price: 110,
      sizes: [
        { mens: 6, available: true },
        { mens: 7, available: false },
        { mens: 8, available: false },
        { mens: 9, available: false },
        { mens: 10, available: true },
        { mens: 11, available: false },
        { mens: 12, available: true },
      ],
      dateListed: 1638028678374,
    },
  },
  {
    id: 'NAiL-lKTpAc',
    productInfo: {
      name: 'Lean Forager II',
      brand: 'New Balance',
      category: 'Lifestyle',
      price: 85,
      salePrice: 75,
      sizes: [
        { mens: 4, available: true },
        { mens: 5.5, available: true },
        { mens: 5, available: true },
        { mens: 6.5, available: true },
        { mens: 7, available: true },
        { mens: 7.5, available: true },
        { mens: 8, available: true },
        { mens: 8.5, available: true },
        { mens: 9, available: true },
        { mens: 10, available: true },
        { mens: 11, available: true },
      ],
      dateListed: 1638028678373,
    },
  },
  {
    id: 'HcqA34-uWo4',
    productInfo: {
      name: 'Straight Shot Low',
      brand: 'Puma',
      category: 'Skate',
      price: 70,
      sizes: [
        { mens: 3, available: true },
        { mens: 4, available: true },
        { mens: 5, available: true },
        { mens: 6, available: false },
        { mens: 7, available: true },
        { mens: 8, available: true },
        { mens: 9, available: true },
        { mens: 10, available: true },
        { mens: 11, available: true },
        { mens: 12, available: true },
        { mens: 13, available: true },
        { mens: 14, available: true },
      ],
      dateListed: 1638028678372,
    },
  },
  {
    id: 'v13tnV6D9lw',
    productInfo: {
      name: 'Old School Hi-Top',
      brand: 'Nike',
      category: 'Skate',
      price: 95,
      sizes: [
        { mens: 5, available: false },
        { mens: 6, available: false },
        { mens: 7, available: true },
        { mens: 8, available: false },
        { mens: 9, available: true },
        { mens: 10, available: false },
        { mens: 11, available: false },
        { mens: 12, available: false },
        { mens: 13, available: true },
      ],
      dateListed: 1638028678371,
    },
  },
  {
    id: '8UqR0nmmZ-k',
    productInfo: {
      name: 'Lightflow Activate',
      brand: 'Puma',
      category: 'Running',
      price: 100,
      sizes: [
        { mens: 3, available: true },
        { mens: 4, available: true },
        { mens: 5, available: true },
        { mens: 6, available: false },
        { mens: 7, available: true },
        { mens: 8, available: true },
        { mens: 9, available: true },
        { mens: 10, available: true },
        { mens: 11, available: true },
        { mens: 12, available: true },
        { mens: 13, available: true },
        { mens: 14, available: true },
      ],
      dateListed: 1638028678370,
    },
  },
  {
    id: '6zO5VKogoZE',
    productInfo: {
      name: 'Ranger Lite – Green',
      brand: 'New Balance',
      category: 'Lifestyle',
      price: 85,
      sizes: [
        { mens: 4, available: true },
        { mens: 5, available: false },
        { mens: 7, available: true },
        { mens: 8, available: false },
        { mens: 9, available: true },
        { mens: 10, available: true },
        { mens: 11, available: true },
      ],
      dateListed: 1638028678369,
    },
  },
  {
    id: 'VleZz-ItaRI',
    productInfo: {
      name: 'Workhorse High',
      brand: 'Timberland',
      category: 'Boot',
      price: 120,
      sizes: [
        { mens: 4, available: true },
        { mens: 5, available: true },
        { mens: 6, available: true },
        { mens: 7, available: true },
        { mens: 8, available: false },
        { mens: 9, available: true },
        { mens: 10, available: true },
        { mens: 11, available: true },
        { mens: 12, available: false },
        { mens: 13, available: true },
        { mens: 14, available: true },
      ],
      dateListed: 1638028678368,
    },
  },
  {
    id: 'Osq7UAVxIOI',
    productInfo: {
      name: 'Cliffjumper',
      brand: 'Timberland',
      category: 'Boot',
      price: 130,
      salePrice: 105,
      sizes: [
        { mens: 5, available: false },
        { mens: 6, available: false },
        { mens: 7, available: true },
        { mens: 8, available: false },
        { mens: 9, available: true },
        { mens: 10, available: false },
        { mens: 11, available: false },
        { mens: 12, available: false },
        { mens: 13, available: true },
      ],
      dateListed: 1638028678367,
    },
  },
  {
    id: '1UKn2qtvBR4',
    productInfo: {
      name: 'Ultra Breathe',
      brand: 'Adidas',
      category: 'Running',
      price: 85,
      sizes: [
        { mens: 5, available: false },
        { mens: 6, available: false },
        { mens: 7, available: true },
        { mens: 8, available: false },
        { mens: 9, available: true },
        { mens: 10, available: false },
        { mens: 11, available: false },
        { mens: 12, available: false },
        { mens: 13, available: true },
      ],
      dateListed: 1638028678366,
    },
  },
  {
    id: 'ezdrvzA1hZw',
    productInfo: {
      name: 'Cloudsoft Pink',
      brand: 'New Balance',
      category: 'Running',
      price: 65,
      sizes: [
        { mens: 4, available: true },
        { mens: 5, available: true },
        { mens: 6.5, available: true },
        { mens: 7, available: true },
        { mens: 7.5, available: true },
        { mens: 8, available: true },
        { mens: 8.5, available: true },
        { mens: 9, available: true },
        { mens: 10, available: true },
        { mens: 11, available: true },
        { mens: 12, available: true },
      ],
      dateListed: 1638028678365,
    },
  },
  {
    id: 'OJTNpLmsSHs',
    productInfo: {
      name: 'Authentic Original – Mustard',
      brand: 'Vans',
      category: 'Skate',
      price: 60,
      sizes: [
        { mens: 3, available: true },
        { mens: 4, available: true },
        { mens: 5, available: true },
        { mens: 6, available: false },
        { mens: 7, available: true },
        { mens: 8, available: true },
        { mens: 9, available: true },
        { mens: 10, available: true },
        { mens: 11, available: true },
        { mens: 12, available: true },
        { mens: 13, available: true },
        { mens: 14, available: true },
      ],
      dateListed: 1638028678364,
    },
  },
];
