export const myProducts = [
  {
    id: 'LxVxPA1LOVM',
    productInfo: {
      name: 'Electric Air – Gray',
      brand: 'Nike',
      category: 'Running',
      price: 90,
      sizes: [
        { mens: 5, available: true },
        { mens: 6, available: true },
        { mens: 7, available: true },
        { mens: 8, available: true },
        { mens: 9, available: false },
        { mens: 10, available: false },
        { mens: 11, available: true },
        { mens: 12, available: false },
        { mens: 13, available: true },
        { mens: 14, available: true },
      ],
    },
  },
  {
    id: 'LG88A2XgIXY',
    productInfo: {
      name: 'Lanemaster – Orange',
      brand: 'Nike',
      category: 'Running',
      price: 75,
      sizes: [
        { mens: 4, available: true },
        { mens: 5, available: true },
        { mens: 6, available: true },
        { mens: 7, available: false },
        { mens: 8, available: true },
        { mens: 9, available: true },
        { mens: 10, available: true },
        { mens: 11, available: true },
        { mens: 12, available: true },
        { mens: 13, available: true },
      ],
    },
  },
  {
    id: 'vraH9m7hfHU',
    productInfo: {
      name: 'Air Quotes',
      brand: 'Nike',
      category: 'Skate',
      price: 110,
      sizes: [
        { mens: 6, available: true },
        { mens: 7, available: false },
        { mens: 8, available: false },
        { mens: 9, available: false },
        { mens: 10, available: true },
        { mens: 11, available: false },
        { mens: 12, available: true },
      ],
    },
  },
  {
    id: 'HcqA34-uWo4',
    productInfo: {
      name: 'Straight Shot Low',
      brand: 'Puma',
      category: 'Skate',
      price: 70,
      sizes: [
        { mens: 3, available: true },
        { mens: 4, available: true },
        { mens: 5, available: true },
        { mens: 6, available: false },
        { mens: 7, available: true },
        { mens: 8, available: true },
        { mens: 9, available: true },
        { mens: 10, available: true },
        { mens: 11, available: true },
        { mens: 12, available: true },
        { mens: 13, available: true },
        { mens: 14, available: true },
      ],
    },
  },
  {
    id: 'v13tnV6D9lw',
    productInfo: {
      name: 'Old School Hi-Top',
      brand: 'Nike',
      category: 'Skate',
      price: 95,
      sizes: [
        { mens: 5, available: false },
        { mens: 6, available: false },
        { mens: 7, available: true },
        { mens: 8, available: false },
        { mens: 9, available: true },
        { mens: 10, available: false },
        { mens: 11, available: false },
        { mens: 12, available: false },
        { mens: 13, available: true },
      ],
    },
  },
  {
    id: 'VleZz-ItaRI',
    productInfo: {
      name: 'Workhorse High',
      brand: 'Timberland',
      category: 'Boot',
      price: 120,
      sizes: [
        { mens: 4, available: true },
        { mens: 5, available: true },
        { mens: 6, available: true },
        { mens: 7, available: true },
        { mens: 8, available: false },
        { mens: 9, available: true },
        { mens: 10, available: true },
        { mens: 11, available: true },
        { mens: 12, available: false },
        { mens: 13, available: true },
        { mens: 14, available: true },
      ],
    },
  },
];
